---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: .virtio

resources:
  - ../2k12

components:
  - ../../components/diskbus-virtio-blk
  - ../../components/interfacemodel-virtio-net
  - ../../components/tablet-virtio
