---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./windows
  - ./rhel
  - ./centos
  - ./ubuntu
  - ./fedora
  - ./cirros
  - ./alpine
  - ./opensuse
  - ./sles
  - ./linux-efi
  - ./linux
  - ./legacy
  - ./debian
  - ./oraclelinux
