---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: highperformance
    target:
      kind: VirtualMachineInstancetype
  - patch: |-
      - op: replace
        path: /metadata/name
        value: highperformance
    target:
      kind: VirtualMachineClusterInstancetype
  - path: highperformance.yaml
    target:
      kind: VirtualMachineInstancetype
  - path: highperformance.yaml
    target:
      kind: VirtualMachineClusterInstancetype
