---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

components:
  - ./metadata
  - ../../components/hyperv
  - ../../components/cpu-topology-sockets
  - ../../components/diskbus-sata
  - ../../components/interfacemodel-e1000e
  - ../../components/tablet-usb
  - ../../components/termination-grace-period

patches:
  - target:
      kind: VirtualMachineClusterPreference
    patch: |-
      - op: replace
        path: /metadata/name
        value: windows
  - target:
      kind: VirtualMachineClusterPreference
    patch: |-
      - op: replace
        path: /metadata/name
        value: windows
